# Generated by Django 5.2.2 on 2025-12-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=14, unique=True, verbose_name='Внутренний ID')),
                ('date', models.DateTimeField(verbose_name='Дата рапорта')),
                ('info', models.TextField(verbose_name='Содержание рапорта')),
            ],
            options={
                'verbose_name': 'Рапорт',
                'verbose_name_plural': 'Рапорты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Статус склада')),
                ('total_place', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая площадь (м²)')),
                ('free_place', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Свободная площадь (м²)')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('role', models.CharField(max_length=100, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=15, unique=True, verbose_name='Внутренний номер заказа')),
                ('date_created', models.DateTimeField(verbose_name='Дата создания')),
                ('date_planned', models.DateTimeField(verbose_name='Планируемая дата')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('status', models.CharField(max_length=15, verbose_name='Статус')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готов к отгрузке')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.manager', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Planinggroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('role', models.CharField(max_length=37, verbose_name='Роль')),
                ('start_work', models.DateTimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('end_work', models.DateTimeField(blank=True, null=True, verbose_name='Окончание работы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planinggroup_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа планирования',
                'verbose_name_plural': 'Группы планирования',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Служба качества',
                'verbose_name_plural': 'Служба качества',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('role', models.CharField(max_length=37, verbose_name='Роль')),
                ('start_work', models.DateTimeField(verbose_name='Начало работы')),
                ('end_work', models.DateTimeField(verbose_name='Окончание работы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_date', models.DateTimeField(verbose_name='Дата утверждения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('current_step', models.PositiveIntegerField(verbose_name='Текущий шаг')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('planinggroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.planinggroup', verbose_name='Группа планирования')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.staff', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало простоя')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание простоя')),
                ('reason', models.CharField(max_length=100, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Устранён')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.order', verbose_name='Заказ')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.staff', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Простой',
                'verbose_name_plural': 'Простои',
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=50, verbose_name='Тип брака')),
                ('found_date', models.DateTimeField(verbose_name='Дата обнаружения')),
                ('fixed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата исправления')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Исправлен')),
                ('info', models.TextField(verbose_name='Описание')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.staff', verbose_name='Обнаружил')),
            ],
            options={
                'verbose_name': 'Брак',
                'verbose_name_plural': 'Брак',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=19, unique=True, verbose_name='Внутренний ID теста')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало теста')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание теста')),
                ('is_passed', models.BooleanField(null=True, verbose_name='Прошёл?')),
                ('standard_compliant', models.BooleanField(null=True, verbose_name='Соответствует стандарту?')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Результаты/комментарий')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.quality', verbose_name='ОТК')),
            ],
            options={
                'verbose_name': 'Химический тест',
                'verbose_name_plural': 'Химические тесты',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=15, unique=True, verbose_name='Номер паспорта')),
                ('info', models.TextField(verbose_name='Содержание')),
                ('created_date', models.DateTimeField(verbose_name='Дата создания')),
                ('issued_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Выдан')),
                ('is_created', models.BooleanField(default=False, verbose_name='Сформирован')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.client', verbose_name='Клиент')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.quality', verbose_name='ОТК')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Паспорт плавки',
                'verbose_name_plural': 'Паспорта плавки',
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=16, unique=True, verbose_name='Внутренний ID рулона')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес (т)')),
                ('thickness', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Толщина (мм)')),
                ('width', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Ширина (мм)')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готов')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.defect', verbose_name='Брак')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.order', verbose_name='Заказ')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.staff', verbose_name='Ответственный')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.test', verbose_name='Тест')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Рулон',
                'verbose_name_plural': 'Рулоны',
                'indexes': [models.Index(fields=['internal_id'], name='core_roll_interna_5c7655_idx'), models.Index(fields=['status'], name='core_roll_status_866b83_idx')],
            },
        ),
    ]
