# Generated by Django 5.2.2 on 2025-12-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='end_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание работы'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
    ]
